



doc: spec.mlw implem.mlw pair_set.mlw partial_map.mlw simple_hashtbl.mlw interface.mlw
	mkdir -p doc
	why3 doc -L . spec.mlw implem.mlw pair_set.mlw partial_map.mlw simple_hashtbl.mlw interface.mlw -o doc
